services:
  - type: web
    name: agro.ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    plan: free
    region: oregon
