services:
  - type: web
    name: crop-disease-detector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    plan: free
    region: oregon
